---
title: "Level 5 Bottle Data"
author: "Thomas Hutchinson"
date: "3/3/2021"
output: 
  pdf_document:
    latex_engine: xelatex
    dev: cairo_pdf
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{IBM Plex Serif Light}
  - \setmonofont{IBM Plex Mono Light}
---
### Load packages and set environment

```{r message=FALSE}

library(tidyverse)
library(inspectdf)
library(hrbrthemes)

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Load Level 5 csv file

```{r}

data <- read_csv("level-5.csv")

# Take out the metadata at the end of the table

#Use the library(flipPlots), using the SankeyDiagram() function.

data <- data %>% 
  select( -"Sample_Date",-"Substrate",-"Weeks",-"Sample_Code",
          -"Submerged",-"Floating",-"Water",-"Vegetation",
          -"Sediment",-"Cut",-"Shredded") %>% 
  pivot_longer(!index, names_to = "otu", values_to = "count")

# Take out the 0 value rows
data <- data %>% 
  filter(count>0)

```

Filter out chloropoasts
```{r}

data <- data %>% 
  filter(!grepl("Chloroplast", otu))

```



25 Top counts

```{r}

data %>% 
  arrange(desc(count)) %>% 
  print(n=25)

```


# Split into five columns
```{r}

t <-data

t <- t %>% separate(otu, c("d", "p", "c", "o", "f"), ";")

t %>% select(p) %>% group_by(p) %>%  summarise(count=n())

```

# Take off prefixes
```{r}
t %>% 
  select(index, d, p, count) %>% 
  filter(p != "__") %>% 
  filter(d != "__") %>% 
  drop_na() %>% 
  mutate(domain = str_sub(d,4),
         phylum = str_sub(p,4)) %>% 
  group_by(domain, phylum) %>% 
  mutate(count = sum(count)) %>% 
  select(index, domain, phylum, count) %>% 
  distinct()
  
 
  
  


             
